import { generateCompletion } from "@anvia/core";
import { getModel } from "../models.js";

const GENERATE_DRAFT_INSTRUCTIONS = `You are the Drafter, an expert content creator. 
Your objective is to take the user's core topic and expand it into a comprehensive first draft. 

You do not just write, you construct. You must establish a clear narrative arc, an appropriate tone, and a logical flow of information. 

Keep the draft engaging, but prioritize structure and substance. `;

const CRITIQUE_DRAFT_INSTRUCTIONS = `You are the Critiquer, a ruthless but highly constructive Senior Editor. 
You will receive an initial draft. 

Your objective is to evaluate both the draft.
Does the draft actually achieve what the Drafter set out to do? 

Analyze the article for:
- Hook and Engagement: Does the opening compel the reader?
- Flow and Structure: Are transitions smooth? Is the pacing off?
- Clarity and Concision: Is there fluff, jargon, or ambiguity?
- Tone and Voice: Is it consistent with the intended audience?

You must include rewrite directive with a clear bulleted list of actionable instructions for the Rewriter. Do not rewrite the article yourself. Instead, give precise commands (e.g., "Cut the second paragraph entirely," 
"Combine sections 3 and 4 for better flow," "Punch up the conclusion to be more action-oriented")
`

const REWRITE_INSTRUCTIONS = `You are the Rewriter, a master copy chief. 
You will be provided with an initial draft and a set of rewrite_directives generated by a Senior Editor (the Critiquer).

Your objective is to produce the final, polished version of the article. You must execute the Critiquer's directives seamlessly, ensuring the final piece flows beautifully, packs a punch, and contains zero fluff or awkward phrasing. 

If a directive from the Critiquer conflicts with the overall flow or seems counterproductive as you write it, 
you have the authority to adapt it.
`

export const generateDraft = async (topic: string) => {
    const prompt = `User's Topic: ${topic}\n\n`;

    const response = await generateCompletion({
        model: getModel('advanced'),
        instructions: GENERATE_DRAFT_INSTRUCTIONS,
        prompt: prompt
    });

    return response.output;
};

export const generateCritique = async (topic: string, draft: string) => {
    const prompt = `User's Topic: ${topic}\n\nDraft: ${draft}\n\n`;

    const response = await generateCompletion({
        model: getModel('advanced'),
        instructions: CRITIQUE_DRAFT_INSTRUCTIONS,
        prompt: prompt
    });

    return response.output;
};

export const generateRewrite = async (
    topic: string,
    draft: string,
    critique: string
) => {
    const prompt = `
    <topic>
    ${topic}
    </topic>

    <initial_draft>
    ${draft}
    </initial_draft>

    <rewrite_directives>
    ${critique}
    </rewrite_directives>
    `;

    const response = await generateCompletion({
        model: getModel('advanced'),
        instructions: REWRITE_INSTRUCTIONS,
        prompt: prompt
    });

    return response.output;
};